Repository Sayak-Bhunia/mystory, pull requests merged in 2024-06, with the labels that each got.

#194 completed this :)
  src/components/importance.jsx
Labels: gssoc, level2

#201 Navbar style changed and fixed
  src/components/Navbar.jsx
Labels: gssoc, level2

#204 Hover effect problem fixed in confess page issue #184
  src/app/(routes)/confess/page.jsx
Labels: gssoc, level1

#206 Fixed profile page
  src/app/api/auth/[...nextauth]/options.js
Labels: gssoc, level3

#207 Account settings
  Settings/README.md
  Settings/index.html
Labels: gssoc, level2

#210 Fixed : improved login & signup page
  src/app/(auth)/signin/page.jsx
  src/app/(auth)/signup/page.jsx
  src/components/UserForm.jsx
  src/components/signInForm.jsx
Labels: gssoc, level2

#211 fix: ui consistency
  src/app/(routes)/search/page.jsx
  src/components/Settings.jsx
  src/components/UserForm.jsx
  src/components/signInForm.jsx
Labels: gssoc, level2

#215 Feat: Added Contributors Page
  README.md
  next.config.mjs
  src/app/(routes)/contributors/ContributorsData.ts
  src/app/(routes)/contributors/page.tsx
  src/components/Navbar.jsx
Labels: gssoc, level3

#217 fix: homepage improvement
  src/app/(routes)/about/page.jsx
  src/app/page.js
  src/components/Testimonials.jsx
  src/components/about/page.jsx
Labels: gssoc, level2

#220 Added Contributors guidelines
  README.md
Labels: gssoc, level1

#221 fix: navbar improvement
  src/components/Navbar.jsx
Labels: gssoc, level3

#226 Added all the contributors who have contributed
  src/app/(routes)/contributors/ContributorsData.ts
Labels: gssoc, level1

#227 Added logo to Footer
  .idea/.gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/mystory.iml
  .idea/vcs.xml
  src/components/Footer/Footer.jsx
Labels: gssoc, level1

#231 Add hover text
  package-lock.json
  package.json
  src/components/Footer/Footer.jsx
Labels: gssoc, level2

#232 404 not found page design improved
  public/404p.png
  src/app/not-found.js
Labels: gssoc, level1

#245 Added 'Back-To-Top' Button on All Pages
  Settings/index.html
  package-lock.json
  package.json
  src/app/(routes)/about/page.jsx
  src/app/(routes)/confess/page.jsx
  src/app/(routes)/contributors/page.tsx
  src/app/(routes)/docs/privacy-policy/page.jsx
  src/app/(routes)/docs/terms/page.jsx
  src/app/(routes)/faqs/page.jsx
  src/app/(routes)/search/advanced/page.jsx
  src/app/(routes)/search/page.jsx
  src/app/globals.css
  src/app/page.js
  src/components/BackToTop.jsx
  src/components/BuyMeACoffee.jsx
  src/components/Settings.jsx
  src/components/UserForm.jsx
  src/components/signInForm.jsx
Labels: gssoc, level2

#262 added the discord
  src/components/Footer/Footer.jsx
Labels: gssoc, level1

#265 Solves issue #234
  package-lock.json
  src/app/(auth)/signin/page.jsx
  src/app/(auth)/signup/page.jsx
  src/app/(routes)/about/page.jsx
  src/app/(routes)/admin/page.tsx
  src/app/(routes)/confess/page.jsx
  src/app/(routes)/contributors/page.tsx
  src/app/(routes)/docs/privacy-policy/page.jsx
  src/app/(routes)/docs/terms/page.jsx
  src/app/(routes)/faqs/page.jsx
  src/app/(routes)/loading.jsx
  src/app/(routes)/profile/page.jsx
  src/app/(routes)/search/advanced/loading.jsx
  src/app/(routes)/search/advanced/page.jsx
  src/app/(routes)/search/loading.jsx
  src/app/(routes)/search/page.jsx
  src/app/(routes)/settings/page.jsx
  src/app/globals.css
  src/app/loading.jsx
  src/app/not-found.js
  src/app/page.js
  src/components/ui/custom-cursor.css
  src/components/ui/custom-cursor.tsx
Labels: gssoc, level3
