Repository Sayak-Bhunia/mystory, pull requests merged in 2024-05, with the labels that each got.

#160 #66 #88 Fixed Profile
  next.config.mjs
  package-lock.json
  package.json
  src/app/(routes)/profile/page.jsx
  src/app/api/auth/[...nextauth]/options.js
  src/components/Navbar.jsx
  src/components/avatar.tsx
Labels: gssoc, level3

#168 Added icons on the navbar
  src/components/Navbar.jsx
Labels: gssoc, level2

#175 fix: GitHub button added
  src/components/Hero/HeroScrollDemo.jsx
Labels: gssoc, level1

#182 fix: change position of git logo
  src/components/Hero/HeroScrollDemo.jsx
Labels: gssoc, level1

#186 Fixed The gap between the Faqs content and navbar is very less .
  src/app/(routes)/faqs/page.jsx
Labels: gssoc, level2

#188 Testimonial section added :)
  src/app/page.js
  src/components/Testimonials.jsx
  src/components/ui/infinite-moving-cards.jsx
  tailwind.config.js
Labels: gssoc, level3

#190 3D card of Sayak-Bhunia added :)
  package-lock.json
  package.json
  public/image/sayakbunia.webp
  src/app/page.js
  src/components/Navbar.jsx
  src/components/about/page.jsx
  src/components/importance.jsx
  src/components/ui/3D-cards.jsx
  src/components/ui/button.jsx
  src/components/ui/hover-effect.jsx
Labels: gssoc, level2
